android/sdk/sdk.v
=> remove unused params

java/keywords.v
This is to fix the issue that causes this PR to fail: https://github.com/vlang/v/pull/8501
=> make the list of keywords public

android/compile.v
=> compile: improve panic messages

.github/workflows/ci.yml, android/compile.v
=> compile: fix cache build, add regression test

README.md, vab.v
=> vab: support ANDROID_SERIAL env variable

java/java.v
=> java: fix semver for single digit version numbers

java/java.v
=> java: ensure full semantic version on JDK version output

README.md, docs/FAQ.md
=> docs: add FAQ

README.md
=> readme: move ANDROID_SERIAL to correct section

README.md
=> readme: fix FAQ link

.github/workflows/ci.yml
=> ci: add more run examples

.github/workflows/ci.yml
=> ci: add first V UI tests

android/compile.v
=> compile: fix NDK header inclusion

.github/workflows/ci.yml
=> ci: add ui rectangles example

.github/workflows/ci.yml, android/deploy.v, android/env/env.v, android/package.v, android/util/util.v, platforms/android/AndroidManifest.xml, platforms/android/res/values/strings.xml, platforms/android/src/io/v/android/V.java, platforms/android/src/io/v/android/VActivity.java, vab.v, vxt/vxt.v
=> all: custom activity support, compile multiple java sources

.github/workflows/ci.yml, android/package.v, vab.v
=> package: fix passing package id from cli flag

docs/FAQ.md
=> docs: change faq design

vab.v
=> vab: tweak a few vebosity levels

vab.v, vxt/vxt.v
=> vab: switch from v.mod to .vab files

vab.v
=> vab: support app_name and icon in .vab files

vab.v
=> vab: apply app_name and icon from .vab only if the have defaults values

android/compile.v, vab.v
=> vab: support setting GLES version from flag

.github/workflows/ci.yml, README.md, android/deploy.v, android/env/env.v, android/keystore.v, android/package.v, android/sdk/sdk.v, android/util/util.v, java/java.v, vab.v
=> vab: aab support

.github/workflows/ci.yml, README.md, vab.v
=> vab: rename --format to --package, add shorthand -p also

.github/workflows/ci.yml, android/env/env.v, android/ndk/ndk.v, android/package.v, android/sdk/sdk.v, vab.v
=> ci: add sdk bootstrap process

.github/workflows/ci.yml
=> ci: remove leftovers from bootstrap addition

android/ndk/ndk.v
=> ndk: comment corrections

.github/workflows/ci.yml, .gitignore, vab.v
=> vab: introduce sub-commands

android/compile.v, vab.v
=> vab: use proper is_prod bool field

v.mod, vab.v
=> vab: get version from vmod at compile time

.github/workflows/ci.yml, android/env/env.v
=> ci: add bootstrap test on macOS

android/deploy.v, vab.v
=> vab: add `--log-raw` mode for unfiltered adb log output

android/ndk/ndk.v, android/sdk/sdk.v
=> sdk: richer debug info with '-d debug_sdk'

.github/workflows/ci.yml, android/env/env.v, android/sdk/sdk.v
=> env: fix manual input to install_opt, closes #92

android/package.v, vab.v
=> doctor: add env vars to output

android/compile.v, android/env/env.v, android/package.v, android/sdk/sdk.v, android/util/util.v, java/java.v, vab.v, vxt/vxt.v
=> vab: update to the new error handling syntax

android/compile.v
=> compile: fix panic message copy-pasta typo

android/compile.v, android/deploy.v, android/env/env.v
=> deploy: add collecting of 'System.out' to --log output

android/deploy.v, vab.v
=> log: add activity name tag to log output

android/deploy.v
=> log: comment too noisy System.out

vxt/vxt.v
=> vxt: more robust V exe detection

android/deploy.v, vab.v
=> doctor: only print sat environment variables

README.md
=> readme: remove stray slash

docs/FAQ.md
=> faq: fix a markdown code formatting

android/deploy.v
=> deploy: disable System.err logs again

.github/workflows/ci.yml, .github/workflows/matrix_ci.yml
=> ci: reduce emulator runs and matrix entries

.github/workflows/ci.yml, .github/workflows/matrix_ci.yml, android/env/env.v, cmd/cleancode.v
=> ci: fix cleancode, work around default SDK build-tools bug

vab.v
=> vab: prepare gc flag

android/env/env.v, android/ndk/ndk.v, android/sdk/sdk.v, android/util/util.v, cache/cache.v, java/java.v
This should speed up things a bit in some setups and for users with HDD's
=> vab: cache results of some disk heavy calls

android/compile.v, platforms/android/AndroidManifest.xml
=> vab: support Android 12 (API 31)

android/compile.v, android/env/env.v, android/package.v, java/java.v, vxt/vxt.v
This is in conjuction to the changes to `IError` in https://github.com/vlang/v/pull/13041
=> change `panic(err.msg)` to the prefered `panic(err)`

.github/workflows/ci_emulator_run.yml, vab.v
V flags is now correctly parsed when passed via `VAB_FLAGS`
=> vab: fix merging of opt.v_flags

android/compile.v
Adds support for the, now default, garbage collection introduced via vlang/v#14577.
=> compile: support vlang/v#14577

android/compile.v, vab.v
Run jobs in parallel per default, add option to disable it: `--no-parallel`
=> compile: support parallel building

vab.v
Prevents the following (until the keystore expires):
```
adb install .... test.apk
3986 KB/s (7870141 bytes in 1.928s)
...
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]
```
=> vab: use system cache dir for debug.keystore

android/ndk/ndk.v
This PR adds support for detecting a version number on NDK directories that are not installed "side-by-side".
This improves the general work with `ndk_version` and makes NDK version handling more explicit - in some cases `ndk-bundle` (or a custom name) can still be returned as a version number - but this PR minimizes the chance greatly.
=> ndk: improve version detection and usage

cli/cli.v, cli/doctor.v, cli/options.v, cli/utils.v, v.mod, vab.v
... making it possible to reuse most of vab's cli API externally
=> vab: move all support functions to new `cli` module

android/compile.v, cli/options.v
This PR fix error for array assign.
=> fix array assign

android/compile.v
This PR fix error for casting to generic.
=> fix error for casting to generic

cli/doctor.v, java/java.v
See https://discord.com/channels/592103645835821068/592294828432424960/1016326287628967986 for reference
=> doctor: warn about potential incompatible JavaRE installs

.github/workflows/docs_ci.yml, README.md, docs/FAQ.md, docs/docs.md
Rendered version here:
https://github.com/Larpon/vab/blob/docs/add-docs-md/docs/docs.md
and here: https://github.com/Larpon/vab/blob/docs/add-docs-md/docs/FAQ.md#i-managed-to-compile-some-external-so-libs-how-do-I-include-them
=> docs: add initial docs.md, update FAQ.md

android/env/env.v
This PR fix string interpolation using `{var}`.
=> env: fix string interpolation using `{var}`

util/shelljob.v
This PR fix ci error of pool.new_pool_processor().
=> fix ci error of pool.new_pool_processor()

tests/vab_error_test.v
This PR fix tests/vab_error_test.v.
=> fix tests/vab_error_test.v

android/compile.v, android/deploy.v, android/env/env.v, android/keystore.v, android/ndk/compiler_flags.v, android/ndk/ndk.v, android/package.v, android/sdk/sdk.v, android/util/util.v, cli/cli.v, cli/doctor.v, cli/options.v, cli/utils.v, cmd/complete.v, docs/docs.md, java/java.v, tests/vab_error_test.v, util/shelljob.v, vab.v, vxt/vxt.v
Ran `v fmt -w .` to transform `$var` to `${var}`
=> all: run vfmt, use consistent string interpolation

README.md, android/ndk/ndk.v
=> add termux

README.md, android/ndk/ndk.v
well I don't know whether you want to video link in read me or not, but you decide ...
=> small sugestion

android/ndk/ndk.v
I'm sorry, but for me not understandable reason $if $else is not stable https://github.com/vlang/v/issues/17262, therefore I sugest this symplify
=> remove $else

cache/cache.v, vab.v
Needed for https://github.com/vlang/v/pull/17923
=> all: change `&Node(0)` to `&Node(unsafe { nil })`

cli/cli.v
Support `-skip-unused` V equivalent
=> cli, compile: support `-skip-unused` v flag

android/deploy.v
Try to increase chance of success
=> deploy: trigger `logcat -c` after package installs, increase sleeps a bit

android/env/env.v, cli/cli.v, cli/utils.v, extra/extra.v, vab.v
... also add suggestions from `cli.subcmds*`
=> extra: support install/remove from local sources

android/android.v, android/package.v, cli/options.v, cli/remedy.v, vab.v
=> cli: introduce notifying of remedies for know problems
